plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.groceryapp'
    compileSdk 35

    signingConfigs {
        release {
            storeFile file('../release-keystore.jks')
            storePassword 'android'
            keyAlias 'groceryapp'
            keyPassword 'android'
        }
    }

    defaultConfig {
        applicationId 'com.example.groceryapp'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

configurations.all {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.room:room-runtime:2.6.1'
    annotationProcessor 'androidx.room:room-compiler:2.6.1'
}
