spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_grocery
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

app:
  upload:
    directory: ./uploads
  ocr:
    tesseract-data-path: /usr/share/tesseract-ocr/5/tessdata

server:
  port: 8080

jwt:
  secret: change-me-in-production
  expiration-ms: 86400000
